name: Deploy to Deno Deploy
on:
  push:
    branches: [deno-deploy]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:        # ğŸ‘ˆ è¿™ä¸€æ®µæ˜¯å¿…é¡»çš„ï¼
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Install npm dependencies
        run: deno task install
      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: livesync-serverpeer
          entrypoint: src/main.ts
